spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
#  security:
#    user:
#      name: root
#      password: root
mybatis:
  type-aliases-package: org.tubetrue01.usercenter.pojo
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 6000

